### ISSUE TITLE
The Student Lab inside the GoDeploy

### ISSUE THREAD

**Issue by cheahengsoon** [GoDeploy/AZ500#1]
May I ask about the student lab inside the GoDeploy?

**Comment by kramit** [comment]
What would you like to ask?

**Comment by cheahengsoon** [comment]
> What would you like to ask?

Because I first time using GoDeploy, the Student lab inside the GoDeploy?

**Comment by kramit** [comment]
Have you been given a training key by your training provider?

**Comment by garethjones294** [comment]
Hi, the labs for AZ500 will be inside the lab environment once completed.  We aim to have all of the AZ500 labs live by the end of April 2019.
